In [36]:
import pandas as pd
import numpy as np

In [37]:
class Meralr:
    def __init__(self):
        self.m=None
        self.b=None
    
    def fit(self,X_train,Y_train):

        num=0
        den=0

        for i in range(len(X_train)):
            num=num+(X_train[i]-X_train.mean())*(Y_train[i]-Y_train.mean())
            den=den+(X_train[i]-X_train.mean())*(X_train[i]-X_train.mean())

        
        self.m=num/den
        self.b=Y_train.mean()-self.m*X_train.mean()

        print(self.m)
        print(self.b)

    def predict(self,X_test):

        return self.m*X_test  +  self.b



            
          
            
        

In [38]:
df=pd.read_csv("placement.csv")

In [39]:
X=df.iloc[:,0:1].values

In [40]:
X

array([[6.89],
       [5.12],
       [7.82],
       [7.42],
       [6.94],
       [7.89],
       [6.73],
       [6.75],
       [6.09],
       [8.31],
       [5.32],
       [6.61],
       [8.94],
       [6.93],
       [7.73],
       [7.25],
       [6.84],
       [5.38],
       [6.94],
       [7.48],
       [7.28],
       [6.85],
       [6.14],
       [6.19],
       [6.53],
       [7.28],
       [8.31],
       [5.42],
       [5.94],
       [7.15],
       [7.36],
       [8.1 ],
       [6.96],
       [6.35],
       [7.34],
       [6.87],
       [5.99],
       [5.9 ],
       [8.62],
       [7.43],
       [9.38],
       [6.89],
       [5.95],
       [7.66],
       [5.09],
       [7.87],
       [6.07],
       [5.84],
       [8.63],
       [8.87],
       [9.58],
       [9.26],
       [8.37],
       [6.47],
       [6.86],
       [8.2 ],
       [5.84],
       [6.6 ],
       [6.92],
       [7.56],
       [5.61],
       [5.48],
       [6.34],
       [9.16],
       [7.36],
       [7.6 ],
       [5.

In [41]:
Y=df.iloc[:,-1:].values

In [42]:
Y

array([[3.26],
       [1.98],
       [3.25],
       [3.67],
       [3.57],
       [2.99],
       [2.6 ],
       [2.48],
       [2.31],
       [3.51],
       [1.86],
       [2.6 ],
       [3.65],
       [2.89],
       [3.42],
       [3.23],
       [2.35],
       [2.09],
       [2.98],
       [2.83],
       [3.16],
       [2.93],
       [2.3 ],
       [2.48],
       [2.71],
       [3.65],
       [3.42],
       [2.16],
       [2.24],
       [3.49],
       [3.26],
       [3.89],
       [3.08],
       [2.73],
       [3.42],
       [2.87],
       [2.84],
       [2.43],
       [4.36],
       [3.33],
       [4.02],
       [2.7 ],
       [2.54],
       [2.76],
       [1.86],
       [3.58],
       [2.26],
       [3.26],
       [4.09],
       [4.62],
       [4.43],
       [3.79],
       [4.11],
       [2.61],
       [3.09],
       [3.39],
       [2.74],
       [1.94],
       [3.09],
       [3.31],
       [2.19],
       [1.61],
       [2.09],
       [4.25],
       [2.92],
       [3.81],
       [1.

In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [44]:
lr=Meralr()

In [45]:
lr.fit(X_train,Y_train)

[0.57513839]
[-1.03626731]


In [46]:
y_pred=lr.predict(X_test[5])

In [47]:
y_pred

array([2.95519314])

In [48]:
Y_test

array([[2.25],
       [2.57],
       [1.94],
       [3.12],
       [2.89],
       [3.57],
       [3.42],
       [2.7 ],
       [2.84],
       [2.93],
       [4.21],
       [2.42],
       [3.82],
       [3.51],
       [2.92],
       [2.17],
       [3.11],
       [2.54],
       [4.6 ],
       [1.48],
       [3.42],
       [2.44],
       [2.26],
       [2.09],
       [2.93],
       [4.14],
       [3.08],
       [2.46],
       [2.18],
       [2.42],
       [3.4 ],
       [2.99],
       [3.18],
       [3.24],
       [2.77],
       [3.44],
       [3.83],
       [2.3 ],
       [3.09],
       [2.99]])

In [49]:
lr.b

array([-1.03626731])

In [50]:
lr.m

array([0.57513839])